-- Kalender/Erinnerungen fuer SozialDoku stabilisieren.
-- Termine muessen dauerhaft in Supabase speicherbar sein; die App erwartet
-- insbesondere die Spalte "erinnerung" fuer aktive Reminder.

create table if not exists public.termine (
  id bigint generated by default as identity primary key,
  titel text not null,
  datum date not null,
  uhrzeit time without time zone,
  klient_id bigint references public.klienten(id) on delete set null,
  fachkraft text,
  ort text,
  notiz text,
  erinnerung boolean not null default false,
  created_by uuid references public.nutzer(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.termine
  add column if not exists titel text,
  add column if not exists datum date,
  add column if not exists uhrzeit time without time zone,
  add column if not exists klient_id bigint references public.klienten(id) on delete set null,
  add column if not exists fachkraft text,
  add column if not exists ort text,
  add column if not exists notiz text,
  add column if not exists erinnerung boolean not null default false,
  add column if not exists created_by uuid references public.nutzer(id) on delete set null,
  add column if not exists created_at timestamptz not null default now();

alter table public.termine
  alter column erinnerung set default false;

update public.termine
   set erinnerung = false
 where erinnerung is null;

alter table public.termine
  alter column erinnerung set not null;

alter table public.termine enable row level security;

drop policy if exists termine_select_authenticated on public.termine;
drop policy if exists termine_insert_authenticated on public.termine;
drop policy if exists termine_delete_authenticated on public.termine;

create policy termine_select_authenticated
  on public.termine
  for select
  to authenticated
  using (true);

create policy termine_insert_authenticated
  on public.termine
  for insert
  to authenticated
  with check (created_by = auth.uid());

create policy termine_delete_authenticated
  on public.termine
  for delete
  to authenticated
  using (true);
